# HunyuanWorld ComfyUI Default Configuration

# Model Settings
models:
  default_precision: "fp16"  # Options: fp32, fp16, bf16
  auto_device_selection: true
  max_memory_usage: 0.8  # Fraction of GPU memory to use
  
  # Model paths (relative to ComfyUI/models/)
  text_to_panorama:
    path: "hunyuan_world/text_to_panorama"
    checkpoint: "model.safetensors"
  
  scene_generator:
    path: "hunyuan_world/scene_generator"
    checkpoint: "model.safetensors"
  
  world_reconstructor:
    path: "hunyuan_world/world_reconstructor"
    checkpoint: "model.safetensors"

# Generation Settings
generation:
  # Text-to-Panorama defaults
  text_to_panorama:
    default_width: 1024
    default_height: 512
    default_steps: 50
    default_guidance_scale: 7.5
    default_scheduler: "DPMSolverMultistep"
  
  # Scene generation defaults
  scene_generator:
    default_depth_estimation: true
    default_semantic_segmentation: true
    default_object_separation: 0.5
    default_layer_count: 5
    default_depth_scale: 1.0
  
  # World reconstruction defaults
  world_reconstructor:
    default_mesh_resolution: 512
    default_texture_resolution: 1024
    default_optimization_steps: 100
    default_smooth_normals: true
    default_generate_materials: true

# Export Settings
export:
  # Default export directory (relative to ComfyUI/)
  default_output_dir: "output/hunyuan_world"
  
  # Mesh export defaults
  mesh_export:
    default_format: "OBJ"
    default_compression: true
    default_include_materials: true
    default_export_textures: true
    
  # Texture export settings
  texture_export:
    default_resolution: 1024
    format: "PNG"
    quality: 95

# Performance Settings
performance:
  # Memory management
  memory:
    auto_clear_cache: true
    cache_cleanup_threshold: 0.9  # Clear cache when memory usage exceeds this
    model_unload_timeout: 300  # Seconds before unloading unused models
  
  # Processing settings
  processing:
    max_batch_size: 4
    enable_mixed_precision: true
    use_torch_compile: false  # Enable if using PyTorch 2.0+
    
# Viewer Settings
viewer:
  default_preview_size: "1024x512"
  supported_preview_sizes:
    - "512x256"
    - "1024x512"
    - "2048x1024"
  
  default_display_mode: "panorama"
  display_modes:
    - "panorama"
    - "depth"
    - "segmentation"
    - "mesh_info"

# Logging Settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_model_loading: true
  log_generation_steps: false
  log_memory_usage: true

# Advanced Settings
advanced:
  # Experimental features
  experimental:
    enable_progressive_generation: false
    enable_multi_gpu: false
    enable_cpu_offload: false
  
  # Custom extensions
  extensions:
    enable_custom_schedulers: true
    enable_custom_samplers: true
    enable_lora_support: false